# application.yml

## Server Setting(서버 포트 세팅)
server:
  port: 11000

# Spring Setting(스프링 설정 세팅)
spring:
  application:
    name: FITMATE

  # MariaDB Setting(데이터베이스 세팅)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:

  # MongoDB Setting
  data:
    mongodb:
      uri:

    # Redis Setting
    redis:
      host:
      port: 6379

  # Session Setting (별도의 최상위 키로 분리)
  session:
    store-type: redis


  # JPA 설정
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  # Mail 설정
  mail:
    host: smtp.naver.com
    port: 587
    username: @naver.com  # 여기에 이메일 주소 입력
    password:          # 여기에 비밀번호 입력
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.naver.com
            protocol: TLSv1.2

# OpenAI (ChatGPT) API Key 설정
openai:
  api:
    key: "${OPENAI_API_KEY}"
    url: "https://api.openai.com/v1/chat/completions"

# API KEYS
api:
  ninjas:
    key: "${API_NINJAS_KEY}"
  youtube:
    key: "${YOUTUBE_API_KEY}"
  papago:
    id: "${PAPAGO_API_ID}"
    secret: "${PAPAGO_API_SECRET}"


